# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  nextjs-dashboard:
    container_name: nextjs-dashboard
    build:
      context: ./nextjs-dashboard
      dockerfile: dev.Dockerfile
    volumes:
      - ./nextjs-dashboard/app:/nextjs-dashboard/app
      - ./nextjs-dashboard/public:/nextjs-dashboard/public
      # It's not necessary to sync the `.next` directory
    restart: always
    # For the moment the port is handled by the my-next-app service (remove, once caddy is set-up)
    ports:
      - 3000:3000
