# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  my-next-app:
    container_name: my-next-app
    build:
      context: ./my-next-app
      dockerfile: dev.Dockerfile
    environment:
      # should be defined in .env
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      # defined in .local.env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./my-next-app/app:/my-next-app/app
      - ./my-next-app/public:/my-next-app/public
      # It's not necessary to sync the `.next` directory
      # Add later once the postgres database is set-up
      # depends_on:
      #   - postgres
    restart: always
    # Remove this once caddy is set-up
    # For the moment the port is handled by the my-next-app service
    ports:
      - 3000:3000
    # Add once there are more than 2 services communicating with each other
    # networks:
    #   - my-network
  
  # Add this at a later stage
  # postgres:
  #   container_name: postgres
  #   build:
  #     context: ./postgres
  #     dockerfile: dev.Dockerfile
  #   environment:
  #     # The only variable required is `POSTGRES_PASSWORD`, the rest are optional
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DATABASE}
  #   restart: always
  #   networks:
  #     - my-network

  # Add this once we need 2 services to communicate with each other
  # Define a network, which allows containers to communicate
  # with each other, by using their container name as a hostname
  # networks:
  #   my-network:
  #     external: true
