# `version` is now deprecated
# https://docs.docker.com/compose/compose-file/#version-top-level-element

services:
  nextjs-dashboard:
    container_name: nextjs-dashboard
    build:
      context: ./nextjs-dashboard
      dockerfile: dev.Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-dashboard/app:/nextjs-dashboard/app
      - ./nextjs-dashboard/public:/nextjs-dashboard/public
      # It's not necessary to sync the `.next` directory
    restart: always
    networks:
      - my-network

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    depends_on:
      - nextjs-dashboard
    networks:
      - my-network

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: dev.Dockerfile
    environment:
      # The only variable required is `POSTGRES_PASSWORD`, the rest are optional
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - my-network

volumes:
  caddy-data:


networks:
  my-network:
    external: true
